export interface Item {
  id: string
  name: string
  caption: string
  image: string
  co2_saved: number
  distance_km: number
  expires_in_hours: number
  urgency: "low" | "medium" | "high"
  claimed: boolean
  category: string
  tags: string[]
}

export const mockItems: Item[] = [
  {
    id: "1",
    name: "Vintage Wooden Chair",
    caption: "Sturdy oak chair from the 1980s. Perfect for a reading nook or home office.",
    image: "/vintage-wooden-chair-furniture.jpg",
    co2_saved: 12.5,
    distance_km: 0.8,
    expires_in_hours: 48,
    urgency: "low",
    claimed: false,
    category: "furniture",
    tags: ["chair", "wooden", "vintage", "oak", "seating", "retro", "office"],
  },
  {
    id: "2",
    name: "Working Microwave",
    caption: "Samsung microwave in great condition. All functions work perfectly.",
    image: "/samsung-microwave-kitchen-appliance.jpg",
    co2_saved: 35.2,
    distance_km: 1.2,
    expires_in_hours: 24,
    urgency: "medium",
    claimed: false,
    category: "electronics",
    tags: ["microwave", "samsung", "kitchen", "appliance", "cooking", "heating"],
  },
  {
    id: "3",
    name: "Kids Bicycle",
    caption: "Blue kids bike suitable for ages 5-8. Minor scratches but rides smoothly.",
    image: "/blue-kids-bicycle.jpg",
    co2_saved: 18.7,
    distance_km: 2.1,
    expires_in_hours: 72,
    urgency: "low",
    claimed: false,
    category: "sports",
    tags: ["bicycle", "bike", "kids", "children", "outdoor", "riding", "blue"],
  },
  {
    id: "4",
    name: "Garden Hose (50ft)",
    caption: "Heavy-duty garden hose with spray nozzle. No leaks, ready to use.",
    image: "/green-garden-hose-coiled.jpg",
    co2_saved: 8.3,
    distance_km: 0.5,
    expires_in_hours: 12,
    urgency: "high",
    claimed: false,
    category: "garden",
    tags: ["hose", "garden", "watering", "outdoor", "yard", "green", "nozzle"],
  },
  {
    id: "5",
    name: "Box of Books (20+)",
    caption: "Collection of fiction and non-fiction books. Great for readers or resellers.",
    image: "/cardboard-box-full-of-books.jpg",
    co2_saved: 15.0,
    distance_km: 1.8,
    expires_in_hours: 96,
    urgency: "low",
    claimed: false,
    category: "books",
    tags: ["books", "reading", "fiction", "non-fiction", "literature", "collection"],
  },
  {
    id: "6",
    name: "Office Desk",
    caption: "Large L-shaped desk with cable management. Some surface wear but solid.",
    image: "/l-shaped-office-desk-modern.jpg",
    co2_saved: 45.0,
    distance_km: 3.2,
    expires_in_hours: 6,
    urgency: "high",
    claimed: false,
    category: "furniture",
    tags: ["desk", "office", "l-shaped", "workspace", "work from home", "table"],
  },
  {
    id: "7",
    name: "Winter Jacket (M)",
    caption: "North Face winter jacket, medium size. Warm and waterproof.",
    image: "/black-north-face-winter-jacket.jpg",
    co2_saved: 22.1,
    distance_km: 0.9,
    expires_in_hours: 48,
    urgency: "medium",
    claimed: false,
    category: "clothing",
    tags: ["jacket", "winter", "north face", "warm", "waterproof", "coat", "medium"],
  },
  {
    id: "8",
    name: "Plant Pots Set",
    caption: "Set of 5 ceramic plant pots in various sizes. Perfect for indoor plants.",
    image: "/ceramic-plant-pots-terracotta.jpg",
    co2_saved: 6.5,
    distance_km: 1.5,
    expires_in_hours: 120,
    urgency: "low",
    claimed: false,
    category: "garden",
    tags: ["pots", "plant", "ceramic", "indoor", "gardening", "planter", "terracotta"],
  },
  {
    id: "9",
    name: "Baby Stroller",
    caption: "Graco stroller in excellent condition. Folds easily, includes rain cover.",
    image: "/baby-stroller-grey-modern.jpg",
    co2_saved: 28.9,
    distance_km: 2.4,
    expires_in_hours: 8,
    urgency: "high",
    claimed: false,
    category: "kids",
    tags: ["stroller", "baby", "graco", "pram", "foldable", "pushchair", "infant"],
  },
  {
    id: "10",
    name: "Standing Fan",
    caption: "Oscillating standing fan with 3 speed settings. Works great for summer.",
    image: "/white-standing-oscillating-fan.jpg",
    co2_saved: 11.2,
    distance_km: 0.6,
    expires_in_hours: 36,
    urgency: "medium",
    claimed: false,
    category: "electronics",
    tags: ["fan", "standing", "oscillating", "cooling", "summer", "electric"],
  },
  {
    id: "11",
    name: "Yoga Mat",
    caption: "Purple yoga mat, 6mm thick. Lightly used, clean and ready for workouts.",
    image: "/purple-yoga-mat-rolled.jpg",
    co2_saved: 3.8,
    distance_km: 1.1,
    expires_in_hours: 168,
    urgency: "low",
    claimed: false,
    category: "sports",
    tags: ["yoga", "mat", "exercise", "fitness", "workout", "purple", "pilates"],
  },
  {
    id: "12",
    name: "Kitchen Table",
    caption: "Solid wood kitchen table seats 4. Minor scratches on surface.",
    image: "/wooden-kitchen-dining-table.jpg",
    co2_saved: 38.5,
    distance_km: 1.9,
    expires_in_hours: 18,
    urgency: "high",
    claimed: false,
    category: "furniture",
    tags: ["table", "kitchen", "dining", "wooden", "seats 4", "wood"],
  },
]

export const categories = [
  { id: "all", name: "All Items", icon: "Grid3X3" },
  { id: "furniture", name: "Furniture", icon: "Sofa" },
  { id: "electronics", name: "Electronics", icon: "Tv" },
  { id: "clothing", name: "Clothing", icon: "Shirt" },
  { id: "sports", name: "Sports", icon: "Dumbbell" },
  { id: "garden", name: "Garden", icon: "TreeDeciduous" },
  { id: "books", name: "Books", icon: "BookOpen" },
  { id: "kids", name: "Kids", icon: "Baby" },
]
